apiVersion: v1
kind: Pod
metadata: 
  name: pod-admin
  namespace: prj-antonio-minelli
  labels:
    app: pod-admin
    env: prod
spec:
  containers:
  - name: pod-admin
    image: docker.io/debian:trixie
    command: ["/bin/bash", "-c", "sleep infinity"]




