apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: prj-antonio-minelli
  labels:
    app: webapp
spec:
  containers:
    - name: web-app
      image: docker.io/bmuschko/web-app:1.0.1
      env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: "Password123"
      ports:
        - containerPort: 3000
          protocol: TCP