apiVersion: v1
kind: Service
metadata:
  name: webapp-app-service
  namespace: prj-antonio-minelli
  labels:
    app: webapp-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      # Porta del service
      port: 3000
      # Porta del container a cui il service deve fare da proxy
      targetPort: 3000
  type: ClusterIP