apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: prj-antonio-minelli
  labels:
    app: mysql-db-service
spec:
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

  